name: CI
on:
 push:
   branches: 
     - master
 
jobs:
 conviso-job:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: ${{secrets.PROJECT_KEY}}
   steps:
   - uses: actions/checkout@v3

   - name: Run SAST
     run: conviso sast run

   - name: run security gate
     run: conviso vulnerability assert-security-rules --rules-file conviso-security-gate.yml
