name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # JOB 1: Executa o Scan da Conviso
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisoast
      env:
        CONVISO_API_KEY: ${{secrets.CONVISO_API_KEY}}
        CONVISO_COMPANY_ID: '443'
    steps:
    - uses: actions/checkout@v4

    - name: Run AST
      # Adicionamos o "|| true" para garantir que o arquivo seja gerado mesmo se houver falhas
      run: |
        export CONVISO_COMPANY_ID='443'
        conviso ast run --vulnerability-auto-close || true

    # Salva o arquivo output.sarif gerado pela Conviso para o próximo Job usar
    - name: Upload SARIF Result
      uses: actions/upload-artifact@v4
      with:
        name: conviso-sarif
        path: /tmp/output.sarif

  # JOB 2: Nosso Quality Gate de QA (VRTA)
  vrta-gate:
    needs: conviso-ast # Só roda depois que o scan terminar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Baixa o relatório gerado pelo Job 1
    - name: Download SARIF Result
      uses: actions/download-artifact@v4
      with:
        name: conviso-sarif
        path: ./

    # Executa a validação usando o Python nativo do Runner
    - name: VRTA - Validar Requisitos de Segurança QA
      run: python vrta_validador.py ./output.sarif