name: CONVISO APPSEC

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisocli
      env:
        FLOW_API_KEY: ${{secrets.CONVISO_API_KEY}}

    steps:

      - uses: actions/checkout@v3

      - name: Set Company ID
        run: |
          # Defina a variável de ambiente COMPANY_ID
          export COMPANY_ID=600
          
          # Imprima o valor do COMPANY_ID para depuração
          echo "Company ID: $COMPANY_ID"

      - name: Run AST
        run: conviso ast run

      - name: Run Security Gate
        run: conviso vulnerability assert-security-rules --rules-file conviso-security-gate.yml
