name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisocli
      env:
        FLOW_API_KEY: ${{secrets.CONVISO_API_KEY}}

    steps:
      - name: Debug API Key 
        run: |
          echo "API Key: ${{secrets.CONVISO_API_KEY}}"

      - uses: actions/checkout@v3

      - name: Run AST
        run: conviso ast run

    
