name: CI
on:
 push:
   branches: master
 pull_request:
   branches: master

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/convisocli
     env:
       FLOW_API_KEY:  f91U_ctrsAdcDY8Dxy6q9Hdem-nYYf-_zqmun-HgL1U
   steps:
   - uses: actions/checkout@v3

   - name: Run AST
     run: conviso ast run
